ALTER SESSION SET CONTAINER=ORCLPDB1;
CREATE USER SINK_USER IDENTIFIED BY SINK_USER DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO SINK_USER;

GRANT CREATE SESSION TO SINK_USER;
GRANT CREATE TABLE TO SINK_USER; -- (caso use auto.create=true)
GRANT CREATE INDEX TO SINK_USER; -- (para criação de PK, FK e índices, se necessário)
GRANT INSERT, UPDATE, DELETE, SELECT ON schema.tabela TO SINK_USER;

CREATE TABLE SINK_USER.TABELA1 (
  ID NUMBER PRIMARY KEY,
  NOME VARCHAR2(50),
  ATUALIZADO_EM TIMESTAMP
);