-- Grants no CDB
GRANT CREATE SESSION TO C##CDC_USER CONTAINER=ALL;
GRANT SET CONTAINER TO C##CDC_USER CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO C##CDC_USER;
-- Permissões de acesso aos dicionários
GRANT SELECT_CATALOG_ROLE TO C##CDC_USER CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE TO C##CDC_USER CONTAINER=ALL;

-- Acesso aos V$ views
GRANT SELECT ON V_$DATABASE TO C##CDC_USER CONTAINER=ALL;
GRANT SELECT ON V_$LOG TO C##CDC_USER CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_LOGS TO C##CDC_USER CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO C##CDC_USER CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO C##CDC_USER CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_SESSION TO C##CDC_USER CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO C##CDC_USER CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO C##CDC_USER CONTAINER=ALL;
GRANT SELECT ON V_$TRANSACTION TO C##CDC_USER CONTAINER=ALL;
GRANT SELECT ON V_$SESSION TO C##CDC_USER CONTAINER=ALL;
GRANT SELECT ON V_$PROCESS TO C##CDC_USER CONTAINER=ALL;

-- LogMiner rights
GRANT EXECUTE ON DBMS_LOGMNR TO C##CDC_USER CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO C##CDC_USER CONTAINER=ALL;

-- Permissão para acessar arquivos de log (necessário para LogMiner)
GRANT SELECT ON V_$LOGFILE TO C##CDC_USER CONTAINER=ALL;
GRANT SELECT ON V_$THREAD TO C##CDC_USER CONTAINER=ALL;
GRANT SELECT ON V_$PARAMETER TO C##CDC_USER CONTAINER=ALL;
GRANT SELECT ON V_$NLS_PARAMETERS TO C##CDC_USER CONTAINER=ALL;

-- Se estiver usando redo log ou archive remoto:
GRANT SELECT ON V_$INSTANCE TO C##CDC_USER CONTAINER=ALL;

--Oracle precisa estar no modo ARCHIVELOG
ARCHIVE LOG LIST;

SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;

--Ativar o Supplemental Logging no banco
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
---------------------------------------------------------------
-- Se não existir schema no PDB, criar:
ALTER SESSION SET CONTAINER=ORCLPDB1;

-- Garantir acesso no PDB
GRANT CONNECT, RESOURCE TO C##CDC_USER;

-- Garantir acesso nas tabelas que você quer capturar
GRANT SELECT ON C##CDC_USER.TABELA1 TO C##CDC_USER;

CREATE TABLE C##CDC_USER.TABELA1 (
  ID NUMBER PRIMARY KEY,
  NOME VARCHAR2(50),
  ATUALIZADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


